# SPDX-License-Identifier: GPL-3.0-only
# Fedora 45 base observed in the 2026-10-05 GNOME 51.0 lab.
FROM fedora@sha256:aacbc26b38361ba0cb3d10f268da40b61b36aed6ed6fe5831a35871636bedb06
RUN dnf -y --setopt=install_weak_deps=False install gnome-shell gjs libsecret python3 unzip dbus-daemon mesa-dri-drivers && dnf clean all
RUN useradd --uid 1000 --create-home sauitest
USER sauitest
ENV LIBGL_ALWAYS_SOFTWARE=1
WORKDIR /tmp
